FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# API xampleapp
Api de notas para usuarios

## Metodos HTTP permitidos

|  Método  |              Descripción               |
| -------- | -------------------------------------- |
| `GET`    | Obtener un recurso o lista de recursos |
| `POST`   | Crear un recurso                       |
| `PUT`    | Actualizar un recurso                  |
| `DELETE` | Eliminar un recurso                    |

## Códigos de Respuesta

| Código |                         Descripción                          |
| ------ | ------------------------------------------------------------ |
| `200`  | Success                                                      |
| `201`  | Success - nuevo recurso creado.                              |
| `204`  | Success - no hay contenido para responder                    |
| `400`  | Bad Request - i.e. su solicitud no se pudo evaluar           |
| `401`  | Unauthorized - usuario no esta autenticado para este recurso |
| `404`  | Not Found - recurso no existe                                |
| `422`  | Unprocessable Entity - i.e. errores de validación            |
| `429`  | Limite de uso excedido, intente mas tarde                    |
| `500`  | Error de servidor                                            |
| `503`  | Servicio no disponible                                       |

## Auth service [/auth]

## SignUp [/auth/signup]

### SignUp a new user [POST]

+ Request (application/json)

        {
            "user": "new user",
            "password": "user password"
        }

+ Response 201 (application/json)

        [
            {
                "user": "new user",
                "password": "user password",
                "id": "user id"
            }
        ]

## Login [/auth/login]

### Login a user [POST]

+ Request (application/json)

        {
            "user": "user",
            "password": "password"
        }

+ Response 200 (application/json)

        [
            {
                success: true,
                message: "Enjoy your token!",
                token: "token",
                userId: "user id"
            }
        ]